export const cityData = [
  "Select Your City",
  "Meerut",
  "Noida",
  "pune",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Meerut",
  "Noida",
  "pune",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Meerut",
  "Noida",
  "pune",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Meerut",
  "Noida",
  "pune",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
]

export const zoneDate = [
  "Select Zone",
  "Central",
  "State",
  "Global",
  "N/A"
]

export const stateData = [
  "Select Your State",
  "Meerut",
  "Noida",
  "pune",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Meerut",
  "Noida",
  "pune",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Meerut",
  "Noida",
  "pune",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Meerut",
  "Noida",
  "pune",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
]

export const companyData2 = [
  "Select Company",
  "Private Company",
  "Public Company",
  "One Person Companies",
  "Charitable Company",
  "Foreign Companies",
  "Government Company",
  "International Financial Services",
  "Nidhi Companies",
  "Producer Company",
  "Limited Liability Partnership",
  "Foreign Limited Liability Partnership",
  "Multi-State Coorperative Society",
  "Branch Office/Project Office/Liaison Office",
  "Consumer Cooperative",
  "Others",
]

export const companyData = [
  "Select Company",
  "Private Company",
  "Public Company",
  "One Person Companies",
  "Charitable Company",
  "Foreign Companies",
  "Government Company",
  "International Financial Services",
  "Nidhi Companies",
  "Producer Company",
  "Limited Liability Partnership",
  "Foreign Limited Liability Partnership",
  "Multi-State Coorperative Society",
  "Branch Office/Project Office/Liaison Office",
  "Consumer Cooperative",
  "Others",
]

export const GstData = [
  "09AAHCC4679J1ZC",
  "10AAHCC4679J1ZC",
  "11AAHCC4679J1ZC",
  "12AAHCC4679J1ZC",
  "13AAHCC4679J1ZC",
  "14AAHCC4679J1ZC",
  "15AAHCC4679J1ZC",
  "16AHCC4679J1ZC",
  "17AAHCC4679J1ZC",
  "18AAHCC4679J1ZC",
  "19AAHCC4679J1ZC",
  "20AAHCC4679J1ZC",
  "21AAHCC4679J1ZC",
  "22AAHCC4679J1ZC",
  "23AAHCC4679J1ZC",
  "24AAHCC4679J1ZC",
  "25AAHCC4679J1ZC",
  "13AAHCC4679J1ZC",
  "14AAHCC4679J1ZC",
  "15AAHCC4679J1ZC",
  "16AHCC4679J1ZC",
  "17AAHCC4679J1ZC",
  "18AAHCC4679J1ZC",
  "19AAHCC4679J1ZC",
  "20AAHCC4679J1ZC",
  "21AAHCC4679J1ZC",
  "22AAHCC4679J1ZC",
  "23AAHCC4679J1ZC",
  "24AAHCC4679J1ZC",
  "25AAHCC4679J1ZC",
]
